import { defineStore } from 'pinia';

export const useAdminStore = defineStore({
  id: 'admin-store',
  state: () => {
    return {
      isAdmin: false,
      activeUser: '',
      adminData: {},
      userCred: { uid: '', token: '' },
      uni: {
        "Abia": ["Michael Okpara University of Agriculture at Umudike", "Abia State University in Uturu", "College of Health Sciences Aba", "Abia State Polytechnic", "Covenant Polytechnic, Aba", "Temple Gate Polytechnic, Abayi", "Valley View Polytechnic, Aba", "Gregory University Uturu", "Rhema University"],
        "Adamawa": ["Adamawa State Polytechnic, Yola", "Adamawa State University, Mubi"],
        "Anambra": ["Anambra State University, Anambra", "Nnamdi Azikiwe University", "Federal Polytechnic, Oko", "Nwafor Orizu University of Education", "Tansian University, Umunya", "Madonna University, Okija", "St Paul's University, Awka"],
        "Akwa Ibom": ["University of Uyo", "Maritime Academy of Nigeria, Oron", "Akwa Ibom State University", "Obong University, Obong Ntak Inyang", "Akwa Ibom State Polytechnic", "Uyo City Polytechnic", "Apex Polytechnic", "Heritage Polytechnic, Eket", "School of Nursing Uyo", "Akwa Ibom State College of Education", "School Of Basic Studies", "College of Arts & Sciences, Nnung Ukim", "Ritman University", "Sure Polytechnic, Ukanafun"],
        "Bauchi": ["Abubakar Tafawa Balewa University", "Federal Polytechnic, Bauchi", "FGGC Bauchi", "Lys Children School", "College of Education - Azare", "National Open University Bauchi"],
        "Bayelsa": ["Bayelsa State College of Health Technology", "Federal Polytechnic, Ekowe", "Federal University, Otueke", "Institute of Science and Technology Yenagoa", "Niger Delta University", "Federal Science and Technical College"],
        "Benue": ["Federal University of Agriculture, Makurdi", "Benue State University, Makurdi", "University of Mkar, Mkar, Gboko", "Benue State Polytechnic, Ugbokolo", "Fidei Polytechnic, Gboko", "Akperan Orshi College of Agriculture Yandev", "Federal College of Education Agasha", "College of Education Oju", "College of Education Kastina Ala"],
        "Borno": ["College of Education Waka-Biu", "Federal Training Centre, Maiduguri", "Federal University of Maiduguri", "MAI University of Maiduguri, Maiduguri", "National Open University of Nigeria", "Ramat Polytechnic Maiduguri", "School of Health and Technology, Maiduguri", "School Of Nursing and Midwifery"],
        "Cross River": ["University of Calabar", "Cross River State University of Technology, Calabar", "Ibrahim Babangida College of Agriculture, Obubra", "Cross River State College of Education, Akamkpa", "College of Health Technology, Iboko", "Technical College Ugep"],
        "Delta": ["Federal University of Petroleum Resources, Effurun", "Delta State University", "Delta State Polytechnic, Ogwashi-Uku", "Delta State Polytechnic, Otefe-Oghara", "Delta State Polytechnic, Ozoro", "College of Education, Agbor", "College of Education, Warri", "Federal College of Education Technical, Asaba", "College of Physical Education, Mosogar", "School of Health Technology, Ughelli", "Petroleum Training Institute, Effurun", "Western Delta University, Oghara", "Novena University, Ogume-Amai", "National Open University of Nigeria", "Delta State School of Marine Technology, Burutu", "Nigerian Maritime University, Okerenkoko", "Conarina School of Maritime & Transport Technology", "University of Information and Communication Technology", "State School of Midwifery", "School of Nursing", "Baptist School of Nursing", "Edwin Clark University", "Eagle Heights University", "Nigerian Naval School", "Nigerian Navy Maritime University"],
        "Ebonyi": ["Ebonyi State University", "Federal University Ndufu Alike Ikwo", "Ebonyi State College of Education Ikwo", "Akanu Ibiam Federal Polytechnic, Unwana", "College of Health Sciences", "Federal College of Agriculture"],
        "Enugu": ["University of Nigeria", "Enugu State University of Science & Technology", "Institute of Management and Technology", "Federal Cooperative College", "Enugu State College of Education Technical", "Caritas University", "Renaissance University", "Federal School of Dental Technology & Therapy", "College of Immaculate Conception", "Our Saviour Institute of Science and Technology", "Federal College of Education", "Caritas University"],
        "Edo": ["Institute of Continuing Education", "Miracle Invasion Leadership Institute", "Nigerian Institute of Computer Science and Professional Studies", "Samuel Adegboyega University", "Ambrose Ali University", "University of Benin", "Bendel State University", "Benin Technical College", "Benson Idahosa University", "College of Education Benin", "Edo State Institute of Technology and Management", "Federal Polytechnic Auchi", "Igbinedion University", "Lighthouse Polytechnic", "National Open University of Nigeria", "Seminary of All Saints", "Shaka Polytechnic", "State School of Nursing", "Usen Polytechnic", "Wellspring University", "World Outreach Bible College"],
        "Ekiti": ["Afe Babalola University", "College of Education", "Crown Polytechnic", "Divisional Teacher's Training College", "Federal Polytechnic", "Federal University Oye Ekiti", "Government Technical College", "His Mercy Computer Institute", "School of Nursing","Bamidele Olumilua university", "University of Ado-Ekiti", "University of Science and Technology, Ifaki"],
        "Gombe": ["College of Administrative and Business Studies, Kumo", "Federal University Kashere", "Federal College of Education (Tech) Gombe", "Gombe State University Tudun Wada", "National Open University Of Nigeria"],
        "Imo": ["Claretian Institute of Philosophy", "African Institute Of Science And Technology", "Alvan Ikoku College Of Education", "College of Business and Legal Studies", "College of Health Science and Technology", "Federal Polytechnic Nekede", "Fed University Of Technology", "Imo State Polytechnic", "Imo State Technological Skills Acquisition Institution", "Imo State University", "National Horticultural Research Institute", "National Open University of Nigeria", "School of Nursing", "Word of Faith Bible Institute"],
        "Jigawa": ["Federal University, Dutse", "Hussaini Adamu Federal Polytechnic", "Informatics Institute of Information Technology", "Jigawa State College Of Agriculture", "Jigawa State College of Education", "Jigawa State Polytechnic"],
        "Kaduna": ["National Teacher's Institute", "Ahmadu Bello University", "Air Force Institute Of Technology", "Ameer Shehu Idris College of Advanced Studies", "Bouyeat Computer Training School", "Dialogue Computer Institute", "ECWA Theological Seminary Kagoro", "Fantsuam Foundation", "Federal College of Chemical and Leather Technology", "Federal College Of Forestry Mechanization", "Federal Cooperative College", "Federal School of Statistics", "Federal Training Centre", "Gralom Computer Institute", "Innovation Institute of Technology", "Kaduna Polytechnic", "Kaduna State College of Education", "Kaduna State University", "National Open University of Nigeria", "Nigerian College Of Aviation Technology", "Nigerian Defence Academy", "Nigerian Institute of Leather and Science Technology", "Nuhu Bamalli Polytechnic", "School Of Health Technology", "St. Gerard's School of Nursing", "St. Luke Anglican School of Nursing", "Federal College of Chemical and Leather Technology", "Federal College Of Education"],
        "Kano": ["Sa'adatu Rimi College Of Education", "Aminu Kano College of Islamic And Legal Studies", "Bayero University", "British Career Training College", "College of Art, Science and Remedial Studies", "Computer Training Institute", "Federal College of Education (Technical)", "Federal College Of Education", "Kano State Polytechnic", "King's Glory University", "Kano University Of Technology", "Nigerian Police Academy", "School of Health Technology"],
        "Katsina": ["Federal College of Education Katsina", "Federal University Dutsin-Ma", "Hassan Usman Katsina Polytechnic", "Isah Kaita College of Education Dutsinma", "Katsina State University", "National Open University of Nigeria", "School of Basic and Remedial Studies Funtua", "School of Health Technology Daura", "School of Health Technology Kankia", "School of Midwifery Malumfashi", "School of Nursing Katsina", "Umaru Musa Yaradua University", "College of Legal and General Studies Daura"],
        "Kebbi": ["Adamu Augie College of Education, Argungu", "Kebbi State University of Science & Tech, Aliero", "Waziri Umaru Federal Polytechnic"],
        "Kogi": ["ECWA School of Nursing (ECWASON)", "Federal College of Education, Okene", "Federal University Of Lokoja", "Kogi State College of Education", "Kogi State College of Nursing", "Kogi State Polytechnic, Lokoja", "Kogi State University, Anyigba", "National Open University of Nigeria", "Salem University, Lokoja", "The Federal Polytechnic Idah"],
        "Kwara": ["College of Nursing, Ilorin", "Federal Polytechnic Offa", "Al-Hikmah University, Ilorin", "University of Ilorin", "Kwara State College of Arabic and Islamic Legal Studies", "Kwara State College of Education", "Kwara State College of Health and Technology", "Kwara State Polytechnic, Ilorin", "Kwara State University", "Landmark University, Omu-Aran", "National Open University of Nigeria"],
        "Lagos": ["The Chartered Institute of Bankers of Nigeria", "Certified Institute of Shipping of Nigeria", "Institute of Chartered Accountants of Nigeria", "Institute of Strategic Management, Nigeria", "Lagos School of Travels and Tourism", "Lagos Business School", "Nigerian Institute Of Public Relations", "Nigerian Institute of Transport Technology", "Nigerian Opportunity Industrialization Centre, Gbagada", "Adeniran Ogunsanya College Of Education", "Administrative Staff College of Nigeria (ASCON)", "Aeroland Aviation School", "African Maritime Academy", "Caleb University, Lagos", "Federal College of Education", "Federal College of Education (Technical), Akoka", "Federal College of Fisheries and Marine Technology", "Federal College Of Orthopedic Technology, Igbobi", "Federal School of Arts and Sciences", "Federal School of Occupational Therapy", "Federal School of Science", "Federal Science and Technical College", "Federal Training Centre", "First Immaculate Computer Institute", "Institute of Chartered Economists of Nigeria", "Institute of Data Processing Management", "karROX ICT Institute", "University of Lagos", "Lagos City Computer College", "Lagos State College of Health Technology, Yaba", "Lagos State Polytechnic", "Lagos University Teaching Hospital", "Life Theological Seminary", "Lagos State University", "Michael Otedola College of Primary Education", "National Open University of Nigeria", "New Horizons Computer Learning Centres", "Nigerian Army School Of Finance And Administration", "Nigerian Army School Of Medical Sciences", "Nigerian Army School of Nursing and Midwifery", "Nigerian Institute of Journalism", "Nigerian Institute Of Management (Chartered)", "Nigerian Institute of Safety Professionals", "Nigerian Law School", "National Institute of Information Technology", "PEFTI Film Institute", "Redeemers University", "Ronik Polytechnic", "Saint Finbarr's College", "Speedway Information Technology Institute", "Times Journalism Institute", "Wolex Polytechnic", "Yaba College Of Technology", "Yetkem Institute of Catering and Hotel Management"],
        "Nasarawa": ["Bingham University, Karu", "Federal University of Technology, Lafia", "National Open University Of Nigeria", "Nasarawa State University, Keffi", "College of Education, Akwanga", "College of Agriculture, Lafia", "Federal Polytechnic Nasarawa", "Nacabs Polytechnic, Akwanga", "Nasarawa State Polytechnic, Lafia"],
        "Niger": ["Federal University of Technology", "Federal University Of Technology, Minna", "National Open University Of Nigeria", "Federal Polytechnic Bida", "Niger State Polytechnic, Zungeru", "College of Administrative and Business Studies, Bida", "College Of Education, Minna", "College for Legal and General Studies", "College of Arts and Islamic Legal Studies", "Federal College of Education, Kontagora", "Federal College of Wildlife Management", "Niger State College of Nursing", "Suleiman Barau Technical College, Suleja"],
        "Ogun": ["Babcock University", "Bells University of Technology", "Crawford University, Igbesa", "Crescent University, Abeokuta", "National Open University Of Nigeria", "Olabisi Onabanjo University, Ago-Iwoye", "University Of Agriculture, Abeokuta", "Abraham Adesanya Polytechnic", "Allover Central Polytechnic", "D S Adegbenro ICT Polytechnic", "Federal Polytechnic Ilaro", "Grace Polytechnic", "Moshood Abiola Polytechnic, Ojere", "The Gateway Polytechnic", "Federal College of Education Abeokuta", "Ifo College of Management and Technology", "Ogun State College Of Health Technology", "Savannah College of Art and Design", "Tai Solarin College Of Education", "Yewa Central College of Education", "Zulikha Abiola College of Arabic And Islamic Studies"],
        "Ondo": ["Adekunle Ajasin University", "Federal University of Technology, Akure", "Rufus Giwa Polytechnic", "Achievers University", "University of Medical Sciences, Ondo", "Ondo State University of Science and Technology", "Wesley University of Science and Technology", "Elizade University", "Adeyemi College of Education, Ondo"],
        "Osun": ["Adeleke University, Ede", "Bowen University, Iwo", "Christwealth University Ifewara", "Fountain University, Osogbo", "Ladoke Akintola University Of Technology", "National Open University of Nigeria", "Obafemi Awolowo University", "Obafemi Awolowo University Staff School", "Oduduwa University", "Osun State University", "University of Abu", "Federal Polytechnic Ede", "Interlink Polytechnic", "Osun State Polytechnic, Iree", "The Polytechnic, Ile-Ife", "Osun State College of Technology, Esa Oke", "Universal College of Technology", "College of Arts and Science, Ile Ife", "Osun State College Of Education Ilesa", "College of Education, Ila-Orangun"],
        "Oyo": ["Ajayi Crowther University, Oyo", "University Of Ibadan", "Lead City University", "National Open University of Nigeria", "The Polytechnic, Ibadan", "St. Winifred Innovative Polytechnic", "Tower Polytechnic", "Best Legacy College of Education", "Federal College of Agriculture, Moor Plantation", "Federal College Of Animal Production and Health", "Federal College of Education", "Federal College of Forestry", "Mufutau Lanihun College of Education", "Oyo State College of Education", "St. Andrews College Of Education, Oyo"],
        "Plateau": ["University Of Jos", "Plateau State University, Bokkos", "Plateau State Polytechnic", "Nigerian College of Accountancy", "College of Arabic and Islamic Studies", "College of Arts, Science and Technology", "College of Education, Jos", "College of Health Technology, Zawan", "Federal College of Education, Pankshin"],
        "Rivers": ["Madonna University", "National Open University Of Nigeria", "University Of Port-Harcourt", "Rivers State University Of Technology", "University of Science and Technology", "Rivers State Polytechnic", "King's College of Commerce", "Federal College of Education (Technical)", "College Of Education, Port-Harcourt", "Rivers State College Of Arts", "Rivers State College of Health Science and Technology"],
        "Sokoto": ["Sokoto State University", "National Open University of Nigeria", "Usmanu Danfodio University", "Usmanu Danfodiyo University Teaching Hospital School Of Nursing", "Sokoto State Polytechnic", "Haliru Binji College Of Art and Science", "Sokoto Teachers' College"],
        "Taraba": ["Taraba State University, Jalingo", "Taraba State Polytechnic, Jalingo", "Federal Science and Technical College", "Taraba State College of Agriculture, Jalingo"],
        "Yobe": ["Buka Abba Ibrahim University, Damaturu", "Federal Polytechnic Damaturu", "College of Administrative and Business Studies, Potiskum", "College of Education, Gashua"],
        "Zamfara": ["Abdul Gusau Polytechnic", "Federal Polytechnic Kaura Namoda", "Kaura Namoda Polytechnic", "College of Islamic Science, Gusau", "Federal University Gusau"],
        "Abuja": ["Nigerian Turkish Nile University", "African University of Science and Technology", "National Open University of Nigeria"]
      }

    };
  },
  actions: {
    SetActiveUser(id, set) {
      if (set) {
        this.activeUser = id;
        localStorage.setItem('activeAdmin', id)
      } else {
        this.activeUser = '';
      }
    },

    SetAdminData(data) {
      this.adminData = data
    },
    SetUserCred(uid, token) {
      this.userCred = { uid: uid, token: token }

    },
    SetAdmin(data) {
      this.isAdmin = data
    },

  },
  getters: {
    // filtersList: state => state.filtersList,
  },
});
